import express from 'express';
import cors from 'cors';
import multer from 'multer';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { createRequire } from 'module';
import axios from 'axios';
import * as cheerio from 'cheerio';
const require = createRequire(import.meta.url);
let pdf = require('pdf-parse/lib/pdf-parse.js');

import { GraphEngineService } from './services/graphEngine.mjs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
app.use(cors());
app.use(express.json({ limit: '10mb' }));
app.use(express.static('public', { etag: false, lastModified: false, setHeaders: (res) => { res.setHeader('Cache-Control', 'no-store'); } }));

const upload = multer({ dest: 'uploads/' });

const SCHEMA_DIR = path.join(__dirname, 'registry', 'schemas');
const GRAPH_DIR = path.join(__dirname, 'registry', 'graphs');
const SPEC_DIR = path.join(__dirname, 'specs');
const SAMPLES_DIR = path.join(__dirname, 'samples');

[SCHEMA_DIR, GRAPH_DIR, SPEC_DIR, SAMPLES_DIR].forEach(dir => {
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
});

/**
 * 1. Return spec text (and cached graph if available) — no LLM
 */
app.get('/api/get-spec', (req, res) => {
    try {
        const standard = req.query.standard;
        if (!standard) return res.status(400).json({ success: false, error: 'standard is required' });

        const safeName = standard.toLowerCase().replace(/\s/g, '_');
        const graphPath = path.join(GRAPH_DIR, `${safeName}_base.json`);
        const schemaPath = path.join(SCHEMA_DIR, `${safeName}_schema.json`);

        // Return cached graph if available
        if (fs.existsSync(graphPath) && fs.existsSync(schemaPath)) {
            const graph = JSON.parse(fs.readFileSync(graphPath, 'utf8'));
            const schema = JSON.parse(fs.readFileSync(schemaPath, 'utf8'));
            return res.json({ success: true, cached: true, graph, schema });
        }

        const specFile = path.join(SPEC_DIR, `${safeName}.txt`);
        if (!fs.existsSync(specFile)) {
            return res.status(404).json({ success: false, error: `No spec found for ${standard} in /specs folder.` });
        }

        const specText = fs.readFileSync(specFile, 'utf8');
        res.json({ success: true, cached: false, specText });
    } catch (error) {
        res.status(500).json({ success: false, error: error.message });
    }
});

/**
 * 2. Return cached schema for a standard
 */
app.get('/api/get-schema', (req, res) => {
    try {
        const standard = req.query.standard;
        const safeName = (standard || '').toLowerCase().replace(/\s/g, '_');
        const schemaPath = path.join(SCHEMA_DIR, `${safeName}_schema.json`);
        if (!fs.existsSync(schemaPath)) return res.json({ success: true, schema: null });
        const schema = JSON.parse(fs.readFileSync(schemaPath, 'utf8'));
        res.json({ success: true, schema });
    } catch (error) {
        res.status(500).json({ success: false, error: error.message });
    }
});

/**
 * 3. Cache graph + schema generated by frontend WebLLM
 */
app.post('/api/cache-graph', (req, res) => {
    try {
        const { standard, graph, schema } = req.body;
        const safeName = standard.toLowerCase().replace(/\s/g, '_');
        fs.writeFileSync(path.join(GRAPH_DIR, `${safeName}_base.json`), JSON.stringify(graph, null, 2));
        fs.writeFileSync(path.join(SCHEMA_DIR, `${safeName}_schema.json`), JSON.stringify(schema, null, 2));
        res.json({ success: true });
    } catch (error) {
        res.status(500).json({ success: false, error: error.message });
    }
});

/**
 * 4. Parse PDF — return extracted text only, no LLM
 */
app.post('/api/parse-pdf', upload.single('file'), async (req, res) => {
    try {
        const dataBuffer = fs.readFileSync(req.file.path);
        const pdfData = await pdf(dataBuffer);
        fs.unlinkSync(req.file.path);
        console.log(`PDF parsed: ${pdfData.text?.length || 0} chars`);
        res.json({ success: true, text: pdfData.text });
    } catch (error) {
        if (req.file?.path && fs.existsSync(req.file.path)) fs.unlinkSync(req.file.path);
        res.status(500).json({ success: false, error: error.message });
    }
});

/**
 * 5. Compare Base with Variant
 */
app.post('/api/compare', (req, res) => {
    try {
        const { graphBase, graphVariant } = req.body;
        const engine = new GraphEngineService();
        const results = engine.compareGraphs(graphBase, graphVariant);
        res.json({ success: true, results });
    } catch (error) {
        res.status(500).json({ success: false, error: error.message });
    }
});

/**
 * 6. Export Comparison Results
 */
app.post('/api/export-comparison', (req, res) => {
    try {
        const { graphBase, graphVariant, comparisonResults, format = 'jsonld' } = req.body;
        const exportData = {
            metadata: { generated: new Date().toISOString(), version: '1.0' },
            comparison: {
                summary: comparisonResults.summary,
                matches: comparisonResults.matches || [],
                missing: comparisonResults.missing || [],
                extensions: comparisonResults.extensions || [],
                conflicts: comparisonResults.conflicts || []
            },
            "@context": {
                "@vocab": "https://governance.ai/ontology/",
                "matches": "https://governance.ai/schema#matches",
                "missing": "https://governance.ai/schema#missing",
                "extensions": "https://governance.ai/schema#extensions",
                "conflicts": "https://governance.ai/schema#conflicts"
            }
        };

        if (format === 'csv') {
            const csv = convertToCSV(comparisonResults);
            res.setHeader('Content-Type', 'text/csv');
            res.setHeader('Content-Disposition', 'attachment; filename="comparison.csv"');
            res.send(csv);
        } else {
            res.json(exportData);
        }
    } catch (error) {
        res.status(500).json({ success: false, error: error.message });
    }
});

/**
 * 7. Generate Metrics Report
 */
app.post('/api/metrics', (req, res) => {
    try {
        const { comparisonResults } = req.body;
        const { summary } = comparisonResults;
        const totalElements = summary.matches + summary.missing + summary.extensions;
        const metrics = {
            compliancePercent: summary.compliancePercent || 0,
            totalBaseElements: summary.totalBaseNodes || 0,
            implementedElements: summary.matches,
            missingElements: summary.missing,
            extensionElements: summary.extensions,
            conflictingRules: summary.conflicts,
            totalVariantElements: summary.totalVariantNodes || 0,
            coverageRatio: totalElements > 0 ? (summary.matches / totalElements * 100).toFixed(2) : 0
        };
        res.json({ success: true, metrics });
    } catch (error) {
        res.status(500).json({ success: false, error: error.message });
    }
});

function convertToCSV(comparisonResults) {
    const rows = [['Category', 'Name', 'Canonical ID', 'Type', 'Source', 'Details']];
    (comparisonResults.matches || []).forEach(m => {
        rows.push(['MATCH', m.node.name, m.canonicalId, m.node.type, m.node.source, m.node.description || '']);
    });
    (comparisonResults.missing || []).forEach(m => {
        rows.push(['MISSING', m.node.name, m.canonicalId, m.node.type, m.node.source, 'Not implemented in variant']);
    });
    (comparisonResults.extensions || []).forEach(e => {
        rows.push(['EXTENSION', e.node.name, 'N/A', e.node.type, e.node.source, 'Outside base framework']);
    });
    (comparisonResults.conflicts || []).forEach(c => {
        const details = (c.diff || []).map(d => `${d.property}: ${d.baseValue} → ${d.targetValue}`).join('; ');
        rows.push(['CONFLICT', c.baseNode.name, c.canonicalId, c.baseNode.type, c.baseNode.source, details]);
    });
    return rows.map(row => row.map(cell => `"${(cell || '').toString().replace(/"/g, '""')}"`).join(',')).join('\n');
}

/**
 * 8. Mock Mode
 */
app.post('/api/mock/base', (req, res) => {
    try {
        const basePath = path.join(SAMPLES_DIR, 'eu_ai_act.jsonld');
        if (!fs.existsSync(basePath)) return res.status(404).json({ success: false, error: 'Sample base JSONLD not found in samples/' });
        const graph = JSON.parse(fs.readFileSync(basePath, 'utf8'));
        const schema = { "@context": graph["@context"] || {}, "@graph": [], name: "EU AI Act (Mock)" };
        res.json({ success: true, graph, schema, cached: true, mock: true });
    } catch (error) {
        res.status(500).json({ success: false, error: error.message });
    }
});

app.post('/api/mock/variant', (req, res) => {
    try {
        const variantPath = path.join(SAMPLES_DIR, 'singapore_model_ai_governance.jsonld');
        if (!fs.existsSync(variantPath)) return res.status(404).json({ success: false, error: 'Sample variant JSONLD not found in samples/' });
        const graph = JSON.parse(fs.readFileSync(variantPath, 'utf8'));
        res.json({ success: true, graph, mock: true });
    } catch (error) {
        res.status(500).json({ success: false, error: error.message });
    }
});

app.get('/api/standards', (req, res) => {
    const files = fs.readdirSync(SPEC_DIR);
    res.json(files.map(f => f.replace('.txt', '').replace(/_/g, ' ').toUpperCase()));
});

/**
 * 9. Web Search — Wikipedia API + Bing scraping, returns combined text
 */
app.post('/api/web-search', async (req, res) => {
    const { query, maxPages = 3 } = req.body;
    if (!query) return res.status(400).json({ success: false, error: 'query is required' });

    const browserHeaders = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
        'Accept-Language': 'en-US,en;q=0.9',
    };

    const pages = [];

    const wikiHeaders = {
        'User-Agent': 'GraphRAGGovernance/1.0 (https://github.com/graphrag; research tool) axios/1.x',
        'Accept': 'application/json'
    };

    // --- Strategy 1: Wikipedia search + article extract (server-side, no origin param) ---
    try {
        const wikiSearch = await axios.get('https://en.wikipedia.org/w/api.php', {
            params: { action: 'query', list: 'search', srsearch: query, format: 'json', srlimit: 3 },
            headers: wikiHeaders,
            timeout: 10000
        });
        const wikiResults = wikiSearch.data?.query?.search || [];
        console.log(`Wikipedia returned ${wikiResults.length} results for "${query}"`);

        for (const result of wikiResults.slice(0, 2)) {
            try {
                const articleResp = await axios.get('https://en.wikipedia.org/w/api.php', {
                    params: { action: 'query', prop: 'extracts', explaintext: true, exlimit: 1, titles: result.title, format: 'json' },
                    headers: wikiHeaders,
                    timeout: 10000
                });
                const pagesObj = articleResp.data?.query?.pages || {};
                const page = Object.values(pagesObj)[0];
                const text = (page?.extract || '').substring(0, 5000);
                if (text.length > 100) {
                    pages.push({
                        url: `https://en.wikipedia.org/wiki/${encodeURIComponent(result.title.replace(/ /g, '_'))}`,
                        title: result.title,
                        text
                    });
                }
            } catch (e) {
                console.warn(`Wikipedia article fetch failed for "${result.title}": ${e.message}`);
            }
        }
    } catch (e) {
        console.warn('Wikipedia search failed:', e.message);
    }

    // --- Strategy 2: DuckDuckGo HTML search + fetch pages ---
    if (pages.length < maxPages) {
        try {
            // Use POST form to DDG HTML (more reliable than lite)
            const ddgResp = await axios.post(
                'https://html.duckduckgo.com/html/',
                `q=${encodeURIComponent(query)}&b=&kl=&df=`,
                { headers: { ...browserHeaders, 'Content-Type': 'application/x-www-form-urlencoded' }, timeout: 12000 }
            );
            const $ = cheerio.load(ddgResp.data);

            const urlsFound = [];
            // DDG HTML results: .result__a links, or .result__url
            $('a.result__a').each((i, el) => {
                if (urlsFound.length >= 5) return;
                const href = $(el).attr('href');
                const title = $(el).text().trim();
                // DDG wraps URLs in a redirect — extract actual URL
                if (href && title.length > 5) {
                    const urlMatch = href.match(/uddg=([^&]+)/);
                    const actualUrl = urlMatch ? decodeURIComponent(urlMatch[1]) : href;
                    if (actualUrl.startsWith('http') && !actualUrl.includes('duckduckgo.com')) {
                        urlsFound.push({ url: actualUrl, title });
                    }
                }
            });

            console.log(`DDG HTML found ${urlsFound.length} URLs for "${query}"`);

            for (const result of urlsFound.slice(0, maxPages - pages.length)) {
                try {
                    const pageResp = await axios.get(result.url, { headers: browserHeaders, timeout: 8000, maxRedirects: 3 });
                    const $p = cheerio.load(pageResp.data);
                    $p('script, style, nav, header, footer, aside, iframe, noscript').remove();
                    const mainText = ($p('article, main, [role="main"], .content, #content').text()
                        || $p('body').text()).replace(/\s+/g, ' ').trim().substring(0, 4000);
                    if (mainText.length > 200) {
                        pages.push({ url: result.url, title: result.title, text: mainText });
                    }
                } catch (e) {
                    console.warn(`Page fetch failed for ${result.url}: ${e.message}`);
                }
            }
        } catch (e) {
            console.warn('DDG search failed:', e.message);
        }
    }

    console.log(`🔍 "${query}": returning ${pages.length} sources`);
    const combinedText = pages.map(p => `## ${p.title}\nSource: ${p.url}\n\n${p.text}`).join('\n\n---\n\n');
    res.json({ success: true, query, pages: pages.map(p => ({ url: p.url, title: p.title })), combinedText });
});

const PORT = 3002;
app.listen(PORT, () => console.log(`🏛️  GraphRAG Governance Engine running on http://localhost:${PORT}`));
